version: "2"

linters:
  default: none

  enable:
    - dogsled
    - errcheck
    - gomodguard
    - gosec
    - govet
    - ineffassign
    - lll
    - misspell
    - staticcheck
    - unused
    - whitespace
    - asciicheck
    - depguard
    - dupl
    - exhaustive
    - gocritic
    - gocyclo
    - funlen

  settings:

    gosec:
      excludes:  
        - G204

    funlen:
      lines: 120
      statements: 70

    gocritic:
      enabled-tags:
        - diagnostic
        - experimental
        - opinionated
        - performance
      disabled-checks:
        - dupImport
        - ifElseChain
        - octalLiteral
        - whyNoLint
        - wrapperFunc
        - paramTypeCombine    
        - emptyFallthrough
        - importShadow        
        - hugeParam            
        - rangeValCopy         
        - sprintfQuotedString

    gocyclo:
      min-complexity: 20

    govet:
      settings:
        printf:
          funcs:
            - (github.com/golangci/golangci-lint/pkg/logutils.Log).Infof
            - (github.com/golangci/golangci-lint/pkg/logutils.Log).Warnf
            - (github.com/golangci/golangci-lint/pkg/logutils.Log).Errorf
            - (github.com/golangci/golangci-lint/pkg/logutils.Log).Fatalf

    dupl:
      threshold: 100

    exhaustive:
      default-signifies-exhaustive: false

    misspell:
      locale: US

    goconst:
      min-len: 2
      min-occurrences: 2

    lll:
      line-length: 950

    depguard:
      rules:
        main:
          deny:
            - pkg: github.com/sirupsen/logrus
              desc: "logging is allowed only by logutils.Log"

  exclusions:
    paths:
      - test/testdata_etc
      - internal/cache
      - internal/renameio
      - internal/robustio
    rules:
      - path: _test\.go
        linters:
          - gomnd
      - linters:
          - gocritic
        text: "unnecessaryDefer:"
        path: ".*"

formatters:
  enable:
    - gofmt
    - goimports
  settings:
    goimports:
      local-prefixes:
        - github.com/golangci/golangci-lint


run:
  timeout: 5m

